### ISSUE TITLE
My Hello World app for Twitter

### ISSUE THREAD

**Issue by scripting** [scripting/twitterHelloWorld#1]
I wrote a simple Hello World app for Twitter. 

You could help me out by trying it and letting me know if it worked. 

It should be obvious what to do. :smile:

http://twitterhello.scripting.com/

**Comment by kvnmlm** [comment]
Worked.

**Comment by scripting** [comment]
@kvnmlm -- thanks for the test.

**Comment by scripting** [comment]
also this isn't a place for a debate -- i just want to find out if this stuff works before presenting it.

**Comment by kvnmlm** [comment]
I thought that as I was typing it.  Fixed.

**Comment by andysylvester** [comment]
Just did it, saw my hello world tweet in my stream.

**Comment by mistersugar** [comment]
Worked for me, too.

**Comment by mterenzio** [comment]
Worked

**Comment by scripting** [comment]
Thanks for the help -- it looks like it works. ;-)

It should because it's a pretty simple program. 

Now I'm going to present it to the Twitter people as an illustration of how much work is involved in doing something very simple, programmatically, with Twitter through the API.
